name : Test Project

on : 
  push:
    branches: [ "main", "*" ]
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      # Step untuk checkout kode dari repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step untuk setup versi Node.js yang akan digunakan
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      - name: Generate Prisma
        run: npx prisma generate

      # Jalankan pengujian menggunakan Jest dengan flag experimental VM modules
      # - name: Run tests
      #   run: npm test
