name : Test Project

on : 
  push:
    branches: [ "main", "coba-ci/cd" ]
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:21
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 21
      - run: npm install
      - run: npm test
